### ISSUE TITLE
users.nickname should be alpha numeric

### ISSUE THREAD

**Issue by ugurarici** [furkanmeraloglu/baby-twitter#1]
With a clean install and seeded database users have regular full names as their `nickname` attribute. This caused by [UserFactory.php](https://github.com/furkanmeraloglu/baby-twitter/blob/f0d2dab36886f56bfc8320d18ed3357d410a2891/database/factories/UserFactory.php#L29) 

Instead of `'nickname' => $this->faker->unique()->name(),` you can use `'nickname' => $this->faker->unique()->userName(),` as seen in [Faker's documentation](https://fakerphp.github.io/formatters/internet/#username). But as seen in it's examples the `userName()` 's created by Faker may have dots `.` in them. Maybe you should clean them (dots) before saving. Or as an alternate to have alpha-numeric random data you can use `'nickname' => $this->faker->unique()-> domainWord(),` Check [documentation](https://fakerphp.github.io/formatters/internet/#domainword) for `domainWord`

Also you need to check user input for `nickname` when registering as a new user and [updating](https://github.com/furkanmeraloglu/baby-twitter/blob/f0d2dab36886f56bfc8320d18ed3357d410a2891/app/Http/Controllers/UserController.php#L109) an existing user record.

You can use [alpha_num](https://laravel.com/docs/8.x/validation#rule-alpha-num) rule to check them with Laravel Validator.

**Comment by furkanmeraloglu** [comment]
UserFactory has been adjusted in accordance with your beneficial suggestions. We've also added a nickname input for the fresh registration. Thank you for your contribution and the time you spent visiting our project.
